name: on-push-workflow
on:
  # run on push, but not on tag release
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  lint-build-deploy:
    timeout-minutes: 10
    name: lint test and build
    # do not run this job if skip ci is in commit message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node v${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: affected:lint
        run: npm run affected:lint -- --all

      - name: affected:test
        run: npm run affected:test -- --all

      - name: generate:json
        run: |
          npx nx run json-generator:generate --args="--user=${{github.actor}}"

      - name: build
        run: npm run build -- -c=production

      - name: scully-build
        run: npm run scully -- --prod=true --no-prompt

      - name: run-lighthouse-ci
        uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: ./lighthouserc.json

      - name: deploy-to-ghpages
        # only execute if on main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/static
