name: on-push-workflow
on:
  # run on push, but not on tag release
  push:
    branches:
      - '**'

jobs:
  lint-build-deploy:
    timeout-minutes: 10
    name: lint test and build
    # do not run this job if skip ci is in commit message
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          # get lfs items
          lfs: true
          # fetch all commits, slower but required to pass to nx
          fetch-depth: 0

      - name: setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.3'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: affected:lint
        run: npm run affected:lint

      - name: affected:test
        run: npm run affected:test

      - name: build
        run: npx nx run client:build:production --statsJson

      - name: purgecss
        run: npx nx run client:purgecss

      - name: Upload json-stats
        uses: actions/upload-artifact@v2
        with:
          name: json-stats
          path: dist/apps/client/stats.json

      - name: scully-build
        run: npx nx run client:scully:prod

      - name: run e2e
        run: npx nx run client-e2e:e2e --headless

      - name: Upload cypress files
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-dist
          path: dist/cypress
          retention-days: 5

      - name: run-lighthouse-ci
        uses: treosh/lighthouse-ci-action@v7
        with:
          configPath: ./lighthouserc.json
          budgetPath: ./lighthouse-budget.json
          temporaryPublicStorage: true
          uploadArtifacts: true

      - name: deploy-to-ghpages
        # only execute if on main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/static
